// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonnelManagementSystem.API.Infrastructure;

#nullable disable

namespace PersonnelManagementSystem.API.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    [Migration("20240310102850_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("department_name");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_number");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.ToTable("education", (string)null);
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_birth");

                    b.Property<DateTime>("DateHire")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_hire");

                    b.Property<DateTime?>("DateTermination")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_termination");

                    b.Property<int>("EmployeeGender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_gender");

                    b.Property<Guid>("EmployeeNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_number");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.SalaryIncrease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryIncreasePercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalaryIncreases");
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Employee", b =>
                {
                    b.HasOne("PersonnelManagementSystem.Models.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasPrincipalKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonnelManagementSystem.Models.Models.Education", "Education")
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasPrincipalKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Education");
                });
#pragma warning restore 612, 618
        }
    }
}
