// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonnelManagementSystem.API.Infrastructure;

#nullable disable

namespace PersonnelManagementSystem.API.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    partial class ManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("PersonnelManagementSystem.API.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("department_name");

                    b.HasKey("Id");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("PersonnelManagementSystem.API.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_number");

                    b.HasKey("Id");

                    b.ToTable("education", (string)null);
                });

            modelBuilder.Entity("PersonnelManagementSystem.API.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_birth");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EducationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeGender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_gender");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_number");

                    b.Property<DateTime?>("FireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_termination");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_hire");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EducationId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("PersonnelManagementSystem.API.Entities.SalaryIncrease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryIncreasePercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalaryIncreases");
                });

            modelBuilder.Entity("PersonnelManagementSystem.API.Entities.Employee", b =>
                {
                    b.HasOne("PersonnelManagementSystem.API.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonnelManagementSystem.API.Entities.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Education");
                });
#pragma warning restore 612, 618
        }
    }
}
