// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonnelManagementSystem.API.Infrastructure;

#nullable disable

namespace PersonnelManagementSystem.API.Migrations
{
    [DbContext(typeof(PersonnelContext))]
    partial class PersonnelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateHire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTermination")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeGender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.SalaryIncrease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryIncreasePercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalaryIncreases");
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Department", b =>
                {
                    b.HasOne("PersonnelManagementSystem.Models.Models.Employee", null)
                        .WithOne("Department")
                        .HasForeignKey("PersonnelManagementSystem.Models.Models.Department", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Education", b =>
                {
                    b.HasOne("PersonnelManagementSystem.Models.Models.Employee", null)
                        .WithOne("Education")
                        .HasForeignKey("PersonnelManagementSystem.Models.Models.Education", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonnelManagementSystem.Models.Models.Employee", b =>
                {
                    b.Navigation("Department")
                        .IsRequired();

                    b.Navigation("Education")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
